### ISSUE TITLE
Discussion over 16 bit

### ISSUE THREAD

**Issue by zbalkan** [zodiacon/DllIconHandler#1]
I am sorry for opening an issue that is not an issue at all. But the discussions are not enabled in the repo, so please consider this as a question in that sense.

The bitness is checked by looking at the indicators of 64 bit images currently. In that case, the 16-bit files are also considered as not-64-bit, hence 32-bit. I know that this is an unusually rare use case, that requires NTVDM or any other platform, but it still made me curious.

What would be the best approach to extend the bitness check?

**Comment by zodiacon** [comment]
Frankly, I did not consider such a case, as 16-bit images cannot be normally used on x64 systems.
But the same scheme could be extended for 16-bit, by examining the PE and figuring out whether this is 16-bit. It's mostly a matter of finding the documentation for the fields to look at, the header format, etc.

**Comment by zbalkan** [comment]
Thank you for the explanation. This was a discussion in ReactOS community, after they managed to run 16-bit software using an open source NTVDM implementation. This can be added as a feature so that the DLL and EXE files would be indicated by the bitness. Thank you again. I am closing the issue.
